In [3]:
import IPython.display
import pandas as pd
from czsc.data.ts_cache import TsDataCache

data_path = "/Users/guyeqi/Documents/Python/data/backtest/data"
dc = TsDataCache(data_path, sdt='20100101', edt='20230112', refresh=False)
thsIndex = dc.ths_index()
allGainianCodes = thsIndex['ts_code'].values.tolist()
thsIndex.sort_values('count',inplace=True)
display(thsIndex)
# for oneGainian in allGainianCodes:
#     gainianDF = dc.ths_member(oneGainian)

       ts_code     name  count exchange list_date type
1    864006.TI     固态电池      1        A  20200102    N
20   864025.TI      无人机      2        A  20200102    N
3    864008.TI     激光雷达      3        A  20200102    N
16   864021.TI      充电桩      3        A  20200102    N
24   864029.TI    川普概念股      3        A  20211001    N
..         ...      ...    ...      ...       ...  ...
213  885806.TI     华为概念    614        A  20181207    N
144  885694.TI      深股通    900        A  20150911    N
253  885867.TI  标普道琼斯A股   1088        A  20190923    N
400  886021.TI     国企改革   1318        A  20221125    N
39   885338.TI     融资融券   3110        A  20100517    N

[408 rows x 6 columns]

In [2]:
# display(dc.ths_member('886026.TI'))